/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HCPRegisterForm: typeof import('./components/HCPRegisterForm.vue')['default']
    InternalPrivacyInfo: typeof import('./components/privacy/InternalPrivacyInfo.vue')['default']
    Logo: typeof import('./components/commons/Logo.vue')['default']
    NButtonMobileVerification: typeof import('./components/commons/NButtonMobileVerification.vue')['default']
    PrivacyInfo: typeof import('./components/privacy/PrivacyInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TakedaRegisterForm: typeof import('./components/TakedaRegisterForm.vue')['default']
  }
}
